### ISSUE TITLE
0.6.3 does not work with Sponge 2005

### ISSUE THREAD

**Issue by ProsperCraft** [hsyyid/SimpleVotifierListener#9]
Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-b23f81b
    SpongeForge: 1.10.2-2171-5.1.0-BETA-2006
    Minecraft Forge: 12.18.2.2171

The server will not start with 0.6.3, it crashes with the following error- 
https://gist.github.com/ProsperCraft/75c6eb87050cd7ade8741ee1a58018ee

Downgraded to https://github.com/hsyyid/SimpleVotifierListener/releases/tag/v0.6.2
and it works fine.

**Comment by GershonR** [comment]
0.6.3 targets API 6, you would need to use SpongeForge "experimental" 1.10.2 builds (API 6)

**Comment by hsyyid** [comment]
Use the 1.10.2 builds. You're using a build built against the API 6, for 1.11
